```{r}

library(tidyverse)
```

```{r}


```

```{r malawi}

blantyre_acute_typhoid <- c('BZD2BA', 'BZD2E5', 'BZD2VN', 'BZD2VP', 'BZD38G', 'BZD3M6', 'BZD3Q2', 'BZD3TV', 'BZD3ZA', 'BZD3ZG', 'BZD41C', 'BZD42B', 'BZD42U', 'BZD435', 'BZD43M', 'BZD44B', 'BZD44T', 'BZD45S', 'BZD45T', 'BZD47S', 'BZD47T', 'BZD4EZ', 'BZD4J5')

# Read the CSV file
malawi_data <- read_csv("/Users/flashton/Dropbox/GordonGroup/STRATAA_pefloxacin_resistant_typhi/data_munging/2021.11.12/STRATAA.ps_enrolment.csv")

# remove every row that was not recruited (pid)
malawi_data <- malawi_data %>% filter(pid != 'NotRecruited') %>% filter(ps07_lims %in% blantyre_acute_typhoid)

# find the ones from the blantyre_acute_typhoid list that aren't in the enrolment information.
#blantyre_acute_typhoid[!blantyre_acute_typhoid %in% data$ps07_lims]

# select the columns we want - ps_42, everything starting ps_44

malawi_data <- malawi_data %>% select(pid, ps07_lims, ps42_stool, starts_with("ps44"))

# checked manually that none of them had stool collection before antibiotics
# add a new column, any_antibiotics, that is TRUE if any of the antibiotics columns are TRUE
malawi_data <- malawi_data %>% mutate(any_antibiotcs = ps44_chloramph + ps44_amox + ps44_coamox + ps44_cotrimox + ps44_cipro + ps44_oxflox + ps44_gatiflox + ps44_azithrom + ps44_cefix + ps44_ceftriax + ps44_unkwabx + ps44_oabx) %>% select(ps07_lims, any_antibiotcs) %>% rename(ps07_lims = lims_id)

write_csv(malawi_data, "/Users/flashton/Dropbox/GordonGroup/STRATAA_pefloxacin_resistant_typhi/data_munging/2021.11.12/Malawi_antibiotic_use.csv")

```




```{r bangladesh}

# read in data
bangladesh_data <- read_csv("/Users/flashton/Dropbox/GordonGroup/STRATAA_pefloxacin_resistant_typhi/data_munging/2021.11.12/Bang_ps.csv")
bgd_acute <- c('TD02-004', 'TD02-008', 'TD02-022', 'TD02-039', 'TD02-081', 'TD02-141', 'TD09-012', 'TD09-022', 'TD09-031', 'TD09-042', 'TD09-050', 'TD09-052', 'TD09-071', 'TD09-087', 'TD09-107', 'TD09-109', 'TD09-121', 'TD09-127', 'TD09-130', 'TD09-131', 'TD09-139', 'TD09-145', 'TD09-155', 'TD09-156', 'TD09-193', 'TD09-203', 'TD09-218', 'TD09-236', 'TD09-272', 'TD09-273', 'TD09-301', 'TD09-638', 'TD09-640', 'TD09-644', 'TD09-648', 'TD09-690', 'TD09-702', 'TD09-761', 'TD09-762', 'TD09-824')

bangladesh_data %>% group_by(strataa_enrol_64_E1_C1) %>%  summarise(n = n())

# filter out the ones that aren't in the list
bangladesh_data <- bangladesh_data %>% filter(Study_ID %in% bgd_acute)

# select the columns we want - Study_ID, everything starting with PS44
# strataa_enrol_64_E1_C1 is "Stool sample collected after antibiotics?"
# so, where that is no, they didn't get antibiotics prior to presentation.
bangladesh_data_stool <- bangladesh_data %>% select(Study_ID,  strataa_enrol_64_E1_C1)
bangladesh_data_stool %>% group_by(strataa_enrol_64_E1_C1) %>%  summarise(n = n())

bangladesh_data <- bangladesh_data %>% select(Study_ID,  strataa_enrol_64_E1_C1) %>%
  mutate(strataa_enrol_64_E1_C1 = if_else(strataa_enrol_64_E1_C1 == "No", "0", strataa_enrol_64_E1_C1)) %>%
    mutate(strataa_enrol_64_E1_C1 = if_else(strataa_enrol_64_E1_C1 == "Yes", "1", strataa_enrol_64_E1_C1)) %>% 
    rename(pid = Study_ID, any_antibiotics = strataa_enrol_64_E1_C1)

write_csv(bangladesh_data, "/Users/flashton/Dropbox/GordonGroup/STRATAA_pefloxacin_resistant_typhi/data_munging/2021.11.12/Bang_antibiotic_use.csv")

```


```{r nepal}
nep_data <- read_csv("/Users/flashton/Dropbox/GordonGroup/STRATAA_pefloxacin_resistant_typhi/data_munging/2021.11.12/Nep_ps.csv")
nep_acute <- c('PS0189', 'PS0284', 'PS0323', 'PS0660', 'PS0664', 'PS0740', 'PS0759', 'PS0941', 'PS0946', 'PS0985', 'PS0991', 'PS1026', 'PS1186', 'PS1248', 'PS1324', 'PS1330', 'PS1353', 'PS1380', 'PS1386', 'PS1393', 'PS1396', 'PS1401', 'PS1410', 'PS1498', 'PS1545', 'PS1580', 'PS1631', 'PS1632', 'PS1874')

nep_data <- nep_data %>% filter(`Study Subject ID` %in% nep_acute)
nep_data <- nep_data %>% select(`Study Subject ID`, strataa_enrol_64_E1_C1)

nep_data <- nep_data %>% select(`Study Subject ID`,  strataa_enrol_64_E1_C1) %>%
  mutate(strataa_enrol_64_E1_C1 = if_else(strataa_enrol_64_E1_C1 == "No", "0", strataa_enrol_64_E1_C1)) %>%
    mutate(strataa_enrol_64_E1_C1 = if_else(strataa_enrol_64_E1_C1 == "Yes", "1", strataa_enrol_64_E1_C1)) %>% 
    rename(pid = `Study Subject ID`, any_antibiotics = strataa_enrol_64_E1_C1)

write_csv(nep_data, "/Users/flashton/Dropbox/GordonGroup/STRATAA_pefloxacin_resistant_typhi/data_munging/2021.11.12/Nep_antibiotic_use.csv")

```

```{r}

# all_data <- bind_rows(malawi_data, bangladesh_data, nep_data)

```