

## Imports
```{r}
library(kableExtra)
library(ggplot2)
library(ggpubr)
```


## Sources

The file handles are set in config.R as they're used by both this script and data_cleaning.

```{r}
source("/Users/flashton/Dropbox/GordonGroup/STRATAA_Microbiome/from_Leo/Leonardos_analysis/bin/core_functions.R")
source("/Users/flashton/Dropbox/GordonGroup/STRATAA_Microbiome/from_Leo/Leonardos_analysis/bin/config.R")
```


## Metadata basics

First do the plots with kruskall wallis comparison between groups to see if there's an overall difference, then do the pairwise tests because KW says there is a difference.


```{r}
metadata <- read_metadata(metadata_handle)

number_per_country <- metadata %>% group_by(Country) %>% summarise(count = n())

number_per_country %>% kbl() %>% kable_styling()

print(sum(number_per_country$count))

baseline_chars <- get_baseline_characteristics(metadata)
baseline_chars %>% kbl(digits = c(NA, NA, 0, 0, 1, 1)) %>% kable_styling()

ggplot(metadata, aes(x = Country, y = Age, fill = Group)) + geom_boxplot() + stat_compare_means(method = 'kruskal.test', label = "p")
comparisons <- list(c("Acute_Typhi", "Carrier"), c("Acute_Typhi", "Control_HealthySerosurvey"), c("Carrier", "Control_HealthySerosurvey"))
# default stat method when doing pairwise tests in wilcoxon.
ggboxplot(metadata, facet.by = "Country", y = "Age", x = "Group", color = "Group") + stat_compare_means(comparisons = comparisons) + rremove("x.text") + rremove("xlab") + rremove("x.ticks") # +rotate_x_text(angle = 45)
```

## pairwise beta

```{r}

run_plot_beta <- function(output_folder, meta, vars_to_plot){
  pcoa.data.handle <- file.path(output_folder, '4_beta', "first_2d_coords.txt")
  pcoa.var.handle <- file.path(output_folder, '4_beta', "pcoa_var.txt")
  pcoa.data <- read_delim(pcoa.data.handle, delim = " ", escape_double = FALSE, trim_ws = TRUE)
  #pcoa.data <- pcoa.data %>% separate(col = Y, sep = '\t', into = c('x', 'y')) %>% rename(ID = X)
  pcoa.var <- read_delim(pcoa.var.handle, delim = " ", escape_double = FALSE, trim_ws = TRUE)
  #pcoa.data <- read_tsv(pcoa.data.handle)
  
  meta_for_beta <- meta %>% select(isolate, Country, Group, Sex, age_bracket, Antibiotics_taken_before_sampling_yes_no_assumptions, group_country, group_antibiotic)
  
  pcoa.data <- left_join(pcoa.data, meta_for_beta, by = c('Sample' = 'isolate'))

  # add some different plots to the below
  # or, change this function to take the variable to colour by
  plots <- plot_beta(pcoa.data, pcoa.var, vars_to_plot)
  return(plots)
}


all_three_vars_to_plot <- c('Country', 'Group', 'Sex', 'age_bracket', 'group_country', 'group_antibiotic')
all_three_plots <- run_plot_beta(output_folder_all_three, metadata, all_three_vars_to_plot)

#all_three_plots$country_plot
#all_three_plots$group_plot
#all_three_plots$sex_plot
#all_three_plots$age_plot
#all_three_plots$group_country_plot
#all_three_plots$group_antibiotic_plot

blantyre_vars_to_plot <- c('Group', 'Sex', 'age_bracket', 'group_antibiotic')
blantyre_plots <- run_plot_beta(output_folder_blantyre, metadata, all_three_vars_to_plot)
blantyre_plots$group_plot
blantyre_plots$sex_plot
blantyre_plots$age_plot
blantyre_plots$group_antibiotic_plot

```

