



## Sources
```{r}
source("/Users/flashton/Dropbox/GordonGroup/STRATAA_Microbiome/from_Leo/Leonardos_analysis/bin/core_functions.R")
source("/Users/flashton/Dropbox/GordonGroup/STRATAA_Microbiome/from_Leo/Leonardos_analysis/bin/config.R")
```

## read in metadata

```{r}
metadata <- read_metadata(metadata_handle)

```


## Setting general params

```{r}
filename_regex = "\\d+_\\d+_\\d+" #for patch and strata
```



## Run beta diversity analysis


```{r}

taxonomic_level <- "species"
all_three_countries <- c('Malawi', 'Bangladesh', 'Nepal')
just_malawi <- c('Malawi')
just_bangladesh <- c('Bangladesh')
just_nepal <- c('Nepal')
malawi_and_bangladesh <- c('Malawi', 'Bangladesh')

run_calculate_beta <- function(output_folder, tax_level, countries, meta, fn_regex, braken_folder){
  filtered_otu.unnormalised <- run_make_filtered_otu_table(output_folder, tax_level, countries, fn_regex, braken_folder, metadata)
  meta_filtered <- meta %>% filter(Country %in% countries)
  beta_dir <- file.path(output_folder, '4_beta')
  if (!dir.exists(beta_dir)){ dir.create(beta_dir) }
  calculate_beta(filtered_otu.unnormalised, meta_filtered, beta_dir)
}

run_calculate_beta(output_folder_all_three, taxonomic_level, all_three_countries, metadata, filename_regex, braken_folder)
run_calculate_beta(output_folder_blantyre, taxonomic_level, just_malawi, metadata, filename_regex, braken_folder)
run_calculate_beta(output_folder_dhaka, taxonomic_level, just_bangladesh, metadata, filename_regex, braken_folder)
run_calculate_beta(output_folder_kathmandu, taxonomic_level, just_nepal, metadata, filename_regex, braken_folder)
run_calculate_beta(output_folder_blantyre_dhaka, taxonomic_level, malawi_and_bangladesh, metadata, filename_regex, braken_folder)

```


## Run PERMANOVA



```{r cache=TRUE}

all_3_d.bray <- readRDS(file.path(output_folder_all_three, '4_beta', 'd.bray.RDS'))
all_3_meta_permanova <- readRDS(file.path(output_folder_all_three, '4_beta', 'meta_for_permanova.RDS'))
pn_all3_csgaa <- adonis(all_3_d.bray~Country*Sex*Group*age_bracket*Antibiotics_taken_before_sampling_yes_no_assumptions, data = all_3_meta_permanova, permutations = 100)
pn_all3_csgaa_with_var_names <- cbind(rownames(pn_all3_csgaa$aov.tab), data.frame(pn_all3_csgaa$aov.tab, row.names = NULL))
pn_all3_csgaa_res <- pn_all3_csgaa_with_var_names %>% rename(variable = `rownames(pn_all3_csgaa$aov.tab)`) %>% mutate(significant = ifelse(`Pr..F.` < 0.01, 'significant', 'not_significant')) %>% arrange(desc(significant), desc(R2)) %>% select(!c(Df, SumsOfSqs, MeanSqs, F.Model))


write_delim(pn_all3_csgaa_res, file.path(output_folder_all_three, '4_beta', 'all_3.permanova.csgaa.tsv'), delim = '\t')

```

